In [1]:
# Célula 1: Autenticação
from google.colab import auth

# Solicita autenticação do usuário
auth.authenticate_user()

print('Authenticated successfully!')

Authenticated successfully!

In [2]:
# Célula 2: Instalação das bibliotecas
!pip install -q gcsfs pyarrow

print('Libraries installed!')

Libraries installed!

In [3]:
# Célula 3: Leitura e visualização dos dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. ESCOLHA QUAL ANÁLISE VOCÊ QUER VER
# Exemplos: 'veteran_hosts_analysis', 'price_seasonality_analysis', 'top_listings_by_reviews', etc.
analysis_name = 'most_reviewed_hosts'


# 3. CONSTRUA O CAMINHO COMPLETO PARA OS DADOS NO GCS
# O 'gs://' indica ao pandas para usar a biblioteca gcsfs que instalamos
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'

print(f"Reading data from: {gcs_path}")

# 4. LEIA OS ARQUIVOS PARQUET DIRETAMENTE PARA UM DATAFRAME PANDAS
try:
    df = pd.read_parquet(gcs_path)

    # 5. MOSTRE O DATAFRAME!
    print(f"\nDisplaying results for: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nAn error occurred: {e}")
    print("Please check if the bucket name and analysis name are correct and if the files exist at the specified location.")

Reading data from: gs://airbnb-data-pedro/results/most_reviewed_hosts

Displaying results for: most_reviewed_hosts

     host_id        host_name  total_reviews  total_listings
0    6000862      Omar Do Rio           5684             214
1  310319158          Suellen           4527             122
2   74463624           Mozart           4155              86
3   46664224           Rafael           4048              52
4    2513825           Newton           3576              65
5   36744189           Monica           3466              41
6   15533343             Yuri           3325              44
7    1982737          Estadia           2806             124
8  347487511          Rodrigo           2710              79
9   29475411  Bruno & Ricardo           2571              30

In [4]:
# Célula para Leitura e Visualização dos Dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. NOME DA ANÁLISE PARA VISUALIZAR
analysis_name = 'price_by_room_type_neighbourhood'

# 3. Caminho completo para os dados no GCS
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'
print(f"Lendo dados de: {gcs_path}")

try:
    # 4. Leia os arquivos Parquet diretamente para um DataFrame Pandas
    df = pd.read_parquet(gcs_path)

    # 5. Mostre o DataFrame!
    print(f"\nExibindo resultados para: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nOcorreu um erro: {e}")
    print("Verifique se o nome do bucket e da análise estão corretos.")

Lendo dados de: gs://airbnb-data-pedro/results/price_by_room_type_neighbourhood

Exibindo resultados para: price_by_room_type_neighbourhood

          room_type    neighbourhood_cleansed  avg_price  total_listings
0       Shared room               São Conrado   25000.00               1
1   Entire home/apt                   Estácio   13113.97              39
2        Hotel room                Copacabana   12688.00               2
3   Entire home/apt                       Joá    7194.78             135
4   Entire home/apt               Coelho Neto    5680.00               2
5   Entire home/apt               São Conrado    4427.25             200
6   Entire home/apt                Portuguesa    2761.88               8
7      Private room                 Itanhangá    2696.15              66
8   Entire home/apt                 Itanhangá    2624.72             101
9   Entire home/apt         Alto da Boa Vista    2378.50              32
10  Entire home/apt                    Galeão    2187.50               2
11  Entire home/apt                Santíssimo    1836.43               7
12  Entire home/apt                   Taquara    1700.75              88
13  Entire home/apt                     Lagoa    1477.78             236
14     Private room                       Joá    1282.63              19
15       Hotel room                    Leblon    1165.00               2
16     Private room                  Curicica    1123.68              24
17  Entire home/apt                     Gávea    1109.83             192
18  Entire home/apt             Rocha Miranda    1095.00               4
19  Entire home/apt                    Leblon    1053.87            1712
20  Entire home/apt                   Ipanema    1040.19            3231
21  Entire home/apt               Cosme Velho    1013.41              56
22     Private room                  Abolição    1000.00               1
23  Entire home/apt                   Inhaúma     999.50               2
24  Entire home/apt           Barra da Tijuca     992.74            3174
25  Entire home/apt                  Abolição     903.17               6
26  Entire home/apt                      Leme     862.47             662
27  Entire home/apt           Jardim Botânico     839.80             157
28     Private room               São Conrado     832.95             258
29  Entire home/apt                 Guaratiba     815.89             140
30  Entire home/apt                   Humaitá     813.01             145
31      Shared room                     Lagoa     777.00               1
32  Entire home/apt             Vargem Grande     774.35             109
33  Entire home/apt                   Vidigal     766.10             188
34     Private room            Cidade de Deus     765.00               6
35  Entire home/apt                    Olaria     764.63               8
36  Entire home/apt                   Rocinha     759.42              26
37  Entire home/apt                    Catete     722.48             328
38  Entire home/apt                Copacabana     710.53           11033
39     Private room                     Zumbi     707.50               2
40  Entire home/apt                      Urca     674.85             128
41  Entire home/apt                   Camorim     672.79             688
42  Entire home/apt  Recreio dos Bandeirantes     663.14            1812
43  Entire home/apt   Freguesia (Jacarepaguá)     662.98              85
44  Entire home/apt            Vargem Pequena     660.73             104
45  Entire home/apt               Laranjeiras     649.80             396
46  Entire home/apt                      Anil     645.45              44
47  Entire home/apt                    Glória     634.95             286
48  Entire home/apt                   Colégio     632.75               4
49       Hotel room                    Centro     631.00               7

In [5]:
# Célula para Leitura e Visualização dos Dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. NOME DA ANÁLISE PARA VISUALIZAR
analysis_name = 'daily_availability'

# 3. Caminho completo para os dados no GCS
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'
print(f"Lendo dados de: {gcs_path}")

try:
    # 4. Leia os arquivos Parquet diretamente para um DataFrame Pandas
    df = pd.read_parquet(gcs_path)

    # 5. Mostre o DataFrame!
    print(f"\nExibindo resultados para: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nOcorreu um erro: {e}")
    print("Verifique se o nome do bucket e da análise estão corretos.")

Lendo dados de: gs://airbnb-data-pedro/results/daily_availability

Exibindo resultados para: daily_availability

   calendar_date  total_listings  available_listings  pct_available
0     2025-03-19            2808                 485          17.27
1     2025-03-20           36748                9054          24.64
2     2025-03-21           42013               15861          37.75
3     2025-03-22           42013               18106          43.10
4     2025-03-23           42013               20855          49.64
5     2025-03-24           42013               22308          53.10
6     2025-03-25           42013               23068          54.91
7     2025-03-26           42013               23371          55.63
8     2025-03-27           42013               24095          57.35
9     2025-03-28           42013               23759          56.55
10    2025-03-29           42013               23485          55.90
11    2025-03-30           42013               24550          58.43
12    2025-03-31           42013               25152          59.87
13    2025-04-01           42013               25304          60.23
14    2025-04-02           42013               26070          62.05
15    2025-04-03           42013               26253          62.49
16    2025-04-04           42013               26264          62.51
17    2025-04-05           42013               26334          62.68
18    2025-04-06           42013               27196          64.73
19    2025-04-07           42013               27813          66.20
20    2025-04-08           42013               28305          67.37
21    2025-04-09           42013               28347          67.47
22    2025-04-10           42013               28119          66.93
23    2025-04-11           42013               27765          66.09
24    2025-04-12           42013               27596          65.68
25    2025-04-13           42013               28159          67.02
26    2025-04-14           42013               28533          67.91
27    2025-04-15           42013               28389          67.57
28    2025-04-16           42013               26820          63.84
29    2025-04-17           42013               23438          55.79

In [6]:
# Célula para Leitura e Visualização dos Dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. NOME DA ANÁLISE PARA VISUALIZAR
analysis_name = 'top_listings_by_reviews'

# 3. Caminho completo para os dados no GCS
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'
print(f"Lendo dados de: {gcs_path}")

try:
    # 4. Leia os arquivos Parquet diretamente para um DataFrame Pandas
    df = pd.read_parquet(gcs_path)

    # 5. Mostre o DataFrame!
    print(f"\nExibindo resultados para: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nOcorreu um erro: {e}")
    print("Verifique se o nome do bucket e da análise estão corretos.")

Lendo dados de: gs://airbnb-data-pedro/results/top_listings_by_reviews

Exibindo resultados para: top_listings_by_reviews

,id,name,number_of_reviews,price,city
0,10730455,"COPACABANA,PRAIA/METRO,MELHOR CUSTO BENEFÍCIO",726,115.0,rio-de-janeiro
1,494903,Casablanca 1 Mediterranean Style Beachfront House,712,276.0,rio-de-janeiro
2,273463,Apto de 2 qtos com vista para Lagoa e garagem,667,493.0,rio-de-janeiro
3,70080,Apart-hotel em Ipanema com garagem e camareira,621,538.0,rio-de-janeiro
4,17865987,COPACABANA BEACH BOUTIQUE LUXURY SPACE 5 *****,620,335.0,rio-de-janeiro
5,996602,Apenas 3 min caminhando até a Praia Copacabana,618,238.0,rio-de-janeiro
6,2092178,Copacabana Beach - Av Atlântica (Sea View - 11th),617,340.0,rio-de-janeiro
7,19181931,"RIO DE JANEIRO,PRÓXIMO PRAIA/METRO,,WI-FI",596,115.0,rio-de-janeiro
8,47118316,Suíte de hotel até 2 pessoas com Café da Manha,594,775.0,rio-de-janeiro
9,14199323,PRIVATE ROOM in Copacabana with AC UNIT,564,132.0,rio-de-janeiro

In [7]:
# Célula para Leitura e Visualização dos Dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. NOME DA ANÁLISE PARA VISUALIZAR
analysis_name = 'superhost_impact'

# 3. Caminho completo para os dados no GCS
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'
print(f"Lendo dados de: {gcs_path}")

try:
    # 4. Leia os arquivos Parquet diretamente para um DataFrame Pandas
    df = pd.read_parquet(gcs_path)

    # 5. Mostre o DataFrame!
    print(f"\nExibindo resultados para: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nOcorreu um erro: {e}")
    print("Verifique se o nome do bucket e da análise estão corretos.")

Lendo dados de: gs://airbnb-data-pedro/results/superhost_impact

Exibindo resultados para: superhost_impact

  host_is_superhost  total_listings  avg_rating  avg_price
0                 f           27945        4.75     786.17
1                 t           12848        4.88     597.75

In [8]:
# Célula para Leitura e Visualização dos Dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. NOME DA ANÁLISE PARA VISUALIZAR
analysis_name = 'occupancy_rate_estimation'

# 3. Caminho completo para os dados no GCS
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'
print(f"Lendo dados de: {gcs_path}")

try:
    # 4. Leia os arquivos Parquet diretamente para um DataFrame Pandas
    df = pd.read_parquet(gcs_path)

    # 5. Mostre o DataFrame!
    print(f"\nExibindo resultados para: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nOcorreu um erro: {e}")
    print("Verifique se o nome do bucket e da análise estão corretos.")

Lendo dados de: gs://airbnb-data-pedro/results/occupancy_rate_estimation

Exibindo resultados para: occupancy_rate_estimation

             listing_id  booked_days  total_days  occupancy_rate
0              24515578          365         365           100.0
1    613014401412604408          365         365           100.0
2              52636787          365         365           100.0
3               2728880          365         365           100.0
4              41563890          365         365           100.0
..                  ...          ...         ...             ...
95   617761612281492865          365         365           100.0
96   946353553693899686          365         365           100.0
97  1035471371659233714          365         365           100.0
98  1290431971846573541          365         365           100.0
99  1297351335923922927          365         365           100.0

[100 rows x 4 columns]

In [9]:
# Célula para Leitura e Visualização dos Dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. NOME DA ANÁLISE PARA VISUALIZAR
analysis_name = 'most_reviewed_hosts'

# 3. Caminho completo para os dados no GCS
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'
print(f"Lendo dados de: {gcs_path}")

try:
    # 4. Leia os arquivos Parquet diretamente para um DataFrame Pandas
    df = pd.read_parquet(gcs_path)

    # 5. Mostre o DataFrame!
    print(f"\nExibindo resultados para: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nOcorreu um erro: {e}")
    print("Verifique se o nome do bucket e da análise estão corretos.")

Lendo dados de: gs://airbnb-data-pedro/results/most_reviewed_hosts

Exibindo resultados para: most_reviewed_hosts

     host_id        host_name  total_reviews  total_listings
0    6000862      Omar Do Rio           5684             214
1  310319158          Suellen           4527             122
2   74463624           Mozart           4155              86
3   46664224           Rafael           4048              52
4    2513825           Newton           3576              65
5   36744189           Monica           3466              41
6   15533343             Yuri           3325              44
7    1982737          Estadia           2806             124
8  347487511          Rodrigo           2710              79
9   29475411  Bruno & Ricardo           2571              30

In [10]:
# Célula para Leitura e Visualização dos Dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. NOME DA ANÁLISE PARA VISUALIZAR
analysis_name = 'price_distribution_by_property_type'

# 3. Caminho completo para os dados no GCS
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'
print(f"Lendo dados de: {gcs_path}")

try:
    # 4. Leia os arquivos Parquet diretamente para um DataFrame Pandas
    df = pd.read_parquet(gcs_path)

    # 5. Mostre o DataFrame!
    print(f"\nExibindo resultados para: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nOcorreu um erro: {e}")
    print("Verifique se o nome do bucket e da análise estão corretos.")

Lendo dados de: gs://airbnb-data-pedro/results/price_distribution_by_property_type

Exibindo resultados para: price_distribution_by_property_type

                        property_type  listing_count  avg_price  median_price
0                  Entire rental unit          25129     717.85         377.0
1         Private room in rental unit           4493     392.29         220.0
2                         Entire home           1931    2005.62         630.0
3                        Entire condo           1665     696.18         405.0
4                Private room in home           1324     279.89         188.0
5                         Entire loft            772     407.42         262.0
6           Entire serviced apartment            714     562.83         380.0
7               Private room in condo            361     296.20         189.0
8   Private room in bed and breakfast            319     388.53         297.0
9                       Room in hotel            220     783.78         476.0
10         Shared room in rental unit            166     168.50         119.0
11                  Entire guesthouse            124     520.50         263.0
12         Private room in guesthouse             96     322.47         204.0
13                       Entire villa             88    6945.01        5340.0
14                 Room in aparthotel             86    1253.80         434.0
15        Private room in guest suite             83     268.59         187.0
16                Shared room in home             78     433.82         116.0
17                 Entire guest suite             59     501.90         264.0
18                          Tiny home             56     196.21         149.0
19          Shared room in guesthouse             56     116.54         120.0

In [11]:
# Célula para Leitura e Visualização dos Dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. NOME DA ANÁLISE PARA VISUALIZAR
analysis_name = 'listings_without_recent_reviews'

# 3. Caminho completo para os dados no GCS
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'
print(f"Lendo dados de: {gcs_path}")

try:
    # 4. Leia os arquivos Parquet diretamente para um DataFrame Pandas
    df = pd.read_parquet(gcs_path)

    # 5. Mostre o DataFrame!
    print(f"\nExibindo resultados para: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nOcorreu um erro: {e}")
    print("Verifique se o nome do bucket e da análise estão corretos.")

Lendo dados de: gs://airbnb-data-pedro/results/listings_without_recent_reviews

Exibindo resultados para: listings_without_recent_reviews

,id,name,last_review_date,number_of_reviews
0,321637,NEW WORLD LODGINGS #Caledonia Room,2012-02-21,1
1,328626,OLYMPIC GAMES 2016 - in Rio de Janeiro,2012-02-21,1
2,786954,AAABSOLUTELY COOLEST 1BR - LEBLON,2013-01-03,1
3,496174,Room 4 World Cup close 2 Maracanã,2013-02-14,1
4,352718,"Copacabana, Posto 06, Um quarto",2013-02-14,2
...,...,...,...,...
95,12007665,Quarto Confortável + Garagem - Casa de Família,2016-08-15,2
96,12844605,"Frente para o mar, com piscina e pé na areia",2016-08-15,1
97,1885051,Room for Couple in Rio de Janeiro,2016-08-16,1
98,9489489,Apt Copacabana de frente para a praia 302,2016-08-16,3
99,2436189,Suite-Copacabana ★★★★ (Safe Street),2016-08-16,9

In [12]:
# Célula para Leitura e Visualização dos Dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. NOME DA ANÁLISE PARA VISUALIZAR
analysis_name = 'new_listings_trend'

# 3. Caminho completo para os dados no GCS
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'
print(f"Lendo dados de: {gcs_path}")

try:
    # 4. Leia os arquivos Parquet diretamente para um DataFrame Pandas
    df = pd.read_parquet(gcs_path)

    # 5. Mostre o DataFrame!
    print(f"\nExibindo resultados para: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nOcorreu um erro: {e}")
    print("Verifique se o nome do bucket e da análise estão corretos.")

Lendo dados de: gs://airbnb-data-pedro/results/new_listings_trend

Exibindo resultados para: new_listings_trend

    first_review_month  count
0           2010-06-01      1
1           2010-07-01      1
2           2010-10-01      1
3           2011-03-01      4
4           2011-05-01      1
..                 ...    ...
166         2024-11-01    888
167         2024-12-01    744
168         2025-01-01   2335
169         2025-02-01    945
170         2025-03-01   2137

[171 rows x 2 columns]

In [13]:
# Célula para Leitura e Visualização dos Dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. NOME DA ANÁLISE PARA VISUALIZAR
analysis_name = 'general_metrics'

# 3. Caminho completo para os dados no GCS
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'
print(f"Lendo dados de: {gcs_path}")

try:
    # 4. Leia os arquivos Parquet diretamente para um DataFrame Pandas
    df = pd.read_parquet(gcs_path)

    # 5. Mostre o DataFrame!
    print(f"\nExibindo resultados para: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nOcorreu um erro: {e}")
    print("Verifique se o nome do bucket e da análise estão corretos.")

Lendo dados de: gs://airbnb-data-pedro/results/general_metrics

Exibindo resultados para: general_metrics

,total_listings,avg_price,min_price,max_price,unique_room_types,unique_neighbourhoods,unique_hosts
0,42013,720.28,30.0,500000.0,4,153,24791

In [14]:
# Célula para Leitura e Visualização dos Dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. NOME DA ANÁLISE PARA VISUALIZAR
analysis_name = 'top_neighborhoods_by_price'

# 3. Caminho completo para os dados no GCS
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'
print(f"Lendo dados de: {gcs_path}")

try:
    # 4. Leia os arquivos Parquet diretamente para um DataFrame Pandas
    df = pd.read_parquet(gcs_path)

    # 5. Mostre o DataFrame!
    print(f"\nExibindo resultados para: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nOcorreu um erro: {e}")
    print("Verifique se o nome do bucket e da análise estão corretos.")

Lendo dados de: gs://airbnb-data-pedro/results/top_neighborhoods_by_price

Exibindo resultados para: top_neighborhoods_by_price

    neighbourhood_cleansed  total_listings  avg_price  min_price  max_price
0                  Estácio              78    6658.01       51.0   500000.0
1                      Joá             140    6653.39      124.0    24643.0
2              São Conrado             313    3001.75      110.0    45000.0
3                 Anchieta               2    2665.00      232.0     5098.0
4                Itanhangá             162    2657.59       72.0   144799.0
5              Coelho Neto               5    2635.60       62.0    11412.0
6               Santíssimo              10    1454.30      109.0    11412.0
7                 Curicica              72    1424.36       61.0    81239.0
8                   Galeão               2    1316.00      257.0     2375.0
9                    Lagoa             261    1278.32      107.0    39600.0
10       Alto da Boa Vista              47    1152.47       99.0     7200.0
11                   Gávea             229    1074.33       98.0    18000.0
12                Cachambi              31    1071.71       30.0    24214.0
13                  Leblon            1707    1023.05      100.0    45313.0
14                 Taquara             162     996.87       48.0    24000.0
15                 Ipanema            3361     968.71       55.0    68000.0
16         Barra da Tijuca            3473     962.61       41.0    39648.0
17  Ricardo de Albuquerque               3     908.67       43.0     1883.0
18                Abolição               6     808.00      120.0     1999.0
19         Jardim Botânico             203     758.93       76.0     8280.0

In [15]:
# Célula para Leitura e Visualização dos Dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. NOME DA ANÁLISE PARA VISUALIZAR
analysis_name = 'veteran_hosts_analysis'

# 3. Caminho completo para os dados no GCS
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'
print(f"Lendo dados de: {gcs_path}")

try:
    # 4. Leia os arquivos Parquet diretamente para um DataFrame Pandas
    df = pd.read_parquet(gcs_path)

    # 5. Mostre o DataFrame!
    print(f"\nExibindo resultados para: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nOcorreu um erro: {e}")
    print("Verifique se o nome do bucket e da análise estão corretos.")

Lendo dados de: gs://airbnb-data-pedro/results/veteran_hosts_analysis

Exibindo resultados para: veteran_hosts_analysis

         host_id       host_name  total_listings first_listing_date
0           3607             Ana               2         2008-10-13
1          11739            Eric               9         2009-03-29
2          19065          Morena               5         2009-05-28
3          34105         Giselle               2         2009-08-26
4          38907    Chris & Gian               1         2009-09-16
...          ...             ...             ...                ...
24782  684484691  Rosemere Maria               2         2025-03-15
24783  684472712      Jacqueline               1         2025-03-15
24784  684637216         Elziane               1         2025-03-16
24785  684805701          Ariane               1         2025-03-17
24786  684789410        Cristian               1         2025-03-17

[24787 rows x 4 columns]

In [16]:
# Célula para Leitura e Visualização dos Dados
import pandas as pd

# 1. ATUALIZE COM O NOME DO SEU BUCKET
BUCKET_NAME = 'airbnb-data-pedro'

# 2. NOME DA ANÁLISE PARA VISUALIZAR
analysis_name = 'price_seasonality_analysis'

# 3. Caminho completo para os dados no GCS
gcs_path = f'gs://{BUCKET_NAME}/results/{analysis_name}'
print(f"Lendo dados de: {gcs_path}")

try:
    # 4. Leia os arquivos Parquet diretamente para um DataFrame Pandas
    df = pd.read_parquet(gcs_path)

    # 5. Mostre o DataFrame!
    print(f"\nExibindo resultados para: {analysis_name}")
    display(df)

except Exception as e:
    print(f"\nOcorreu um erro: {e}")
    print("Verifique se o nome do bucket e da análise estão corretos.")

Lendo dados de: gs://airbnb-data-pedro/results/price_seasonality_analysis

Exibindo resultados para: price_seasonality_analysis

              city  month  average_price
0   rio-de-janeiro      1         854.40
1   rio-de-janeiro      2         848.61
2   rio-de-janeiro      3         826.81
3   rio-de-janeiro      4         788.38
4   rio-de-janeiro      5         765.39
5   rio-de-janeiro      6         757.84
6   rio-de-janeiro      7         783.19
7   rio-de-janeiro      8         786.10
8   rio-de-janeiro      9         812.20
9   rio-de-janeiro     10         846.20
10  rio-de-janeiro     11         843.69
11  rio-de-janeiro     12         850.48